### PR TITLE
Language Data Gen & More OS Icons

### PR DESCRIPTION
**Pull request by wired-tomato**
Exactly what it sounds like, I've added (semi)automatic language data gen and more OS icons.

### CODE REVIEW

**Review by blryface — CHANGES_REQUESTED** [review]
Please remove Manjaro, make sure all textures you added are 512x512 in resolution, and that all lang is the same as old, manual ones.

**Comment by wired-tomato** [comment]
by semi-automatic i meant their done in code as opposed to manual JSON
Example:
```kotlin
registerSimpleItem("arch_linux", "Arch Linux");
```
The second parameter gets passed to datagen and the item translation key is mapped to the name when the `runDatagen` task is called.

I'll find 512x icons

**Comment by blryface** [comment]
Would that not make translations harder? Well, not that we'll need any, but would it not?

**Comment by wired-tomato** [comment]
Review my code, the system I have setup allows for more languages via the `LanguageProvider` class I have setup, translations won't be any harder. And you could always write them manually nothing is preventing you from doing so.

**Comment by blryface** [comment]
Seems good to me

**Pull request merged**
